version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 4444:5432
    env_file:
      - .env.test

  node:
    container_name: exercicio-cdci
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
     - .env.docker
